/**
 * XTRM footer: single-line statusline — path/branch, context/model, beads counts.
 *
 * xtrm-64pl0: the footer is a pure cache READER. It renders one line combining
 * path/branch, context usage, provider/model/thinking, and compact beads counts read
 * from the on-disk cache (.xtrm/cache/beads-status.json). It never spawns bd, never
 * refreshes the cache via a subprocess, and exposes no expandable tree/toggle. The
 * cache is regenerated by beads hooks elsewhere; stale/unavailable is acceptable and
 * rendered as-is.
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { truncateToWidth } from "@earendil-works/pi-tui";
import { basename, dirname, join, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";

import { SubprocessRunner } from "../../src/core";

type CacheIssue = { id: string; title: string | null; status: string; parent?: string };
type BeadsCache = {
	v: number;
	ts: number;
	stale: boolean;
	counts: { open: number; in_progress: number; blocked: number };
	activeIssues: CacheIssue[];
	activeEpic: { id: string; title: string | null; closed: number; total: number } | null;
};
type CacheModule = {
	resolveMainRoot(cwd: string): string;
	readCache(mainRoot: string): BeadsCache | null;
	formatCompact(data: BeadsCache | null, options: { cols: number; color?: boolean }): string;
};

const CACHE_MODULE = ".xtrm/hooks/beads-status-cache.mjs";
const CACHE_TTL = 5000;
const REFRESH_TIMEOUT_MS = 2000;
const TOOL_RESULT_REFRESH_DELAY_MS = 200;
const FOOTER_REAPPLY_DELAY_MS = 40;

// XTRM accent for the model name (#9a8bff) — theme.fg() only accepts named tokens
// and throws on raw hex, so emit the truecolor SGR directly (the footer already
// uses raw SGR escapes for bold path and thinking level).
const XTRM_ACCENT = "\x1b[38;2;154;139;255m";

export type FooterSectionRenderer = (width: number) => string[];

const footerSections = new Map<string, FooterSectionRenderer>();
let footerDisabled = false;

// Fleet composition seam (unitAI-beqby.2): registers lines rendered below the
// statusline. Re-registering a key replaces it. When the footer is
// absent/disabled the call is a silent no-op returning a no-op unregister.
export function registerFooterSection(key: string, renderBelow: FooterSectionRenderer): () => void {
	const noop = (): void => {};
	if (footerDisabled) return noop;
	if (typeof key !== "string" || !key || typeof renderBelow !== "function") return noop;
	footerSections.set(key, renderBelow);
	return () => {
		if (footerSections.get(key) === renderBelow) footerSections.delete(key);
	};
}

// Fleet hook publication (unitAI-plbug): the fleet looks up
// globalThis.__registerFooterSection and falls back to belowEditor when absent.
// Publish on load, clear on unload. Never throws; silent without globalThis.
function publishFooterHook(): void {
	try {
		if (typeof globalThis === "undefined") return;
		(globalThis as Record<string, unknown>).__registerFooterSection = registerFooterSection;
	} catch {
		// Silent: hook publication must never break load.
	}
}

function clearFooterHook(): void {
	try {
		if (typeof globalThis === "undefined") return;
		const g = globalThis as Record<string, unknown>;
		if (g.__registerFooterSection === registerFooterSection) delete g.__registerFooterSection;
	} catch {
		// Silent: hook cleanup must never break unload.
	}
}

publishFooterHook();

function formatTokens(count: number): string {
	if (count < 1000) return count.toString();
	if (count < 10_000) return `${(count / 1000).toFixed(1)}k`;
	if (count < 1_000_000) return `${Math.round(count / 1000)}k`;
	return count < 10_000_000 ? `${(count / 1_000_000).toFixed(1)}M` : `${Math.round(count / 1_000_000)}M`;
}

function parseGitFlags(porcelain: string): string {
	let modified = false;
	let staged = false;
	let deleted = false;
	for (const line of porcelain.split("\n").filter(Boolean)) {
		if (/^ M|^AM|^MM/.test(line)) modified = true;
		if (/^A |^M /.test(line)) staged = true;
		if (/^ D|^D /.test(line)) deleted = true;
	}
	return `${modified ? "*" : ""}${staged ? "+" : ""}${deleted ? "-" : ""}`;
}

export default function registerCustomFooter(pi: ExtensionAPI): void {
	publishFooterHook();
	let capturedCtx: any = null;
	let cacheModule: CacheModule | null = null;
	let mainRoot = "";
	let beadsCache: BeadsCache | null = null;
	let requestRender: (() => void) | null = null;
	let branchChangeUnsub: (() => void) | null = null;
	let footerReapplyTimer: ReturnType<typeof setTimeout> | null = null;
	let runtimeRefreshTimer: ReturnType<typeof setTimeout> | null = null;
	let cacheSyncTimer: ReturnType<typeof setInterval> | null = null;
	let refreshingRuntime = false;
	let runtimeState = { branch: null as string | null, gitStatus: "", lastFetch: 0 };

	const cwd = () => capturedCtx?.cwd || process.cwd();
	const run = (command: string, args: string[], timeoutMs = REFRESH_TIMEOUT_MS) =>
		SubprocessRunner.run(command, args, { cwd: cwd(), timeoutMs });

	const loadCacheModule = async (): Promise<void> => {
		if (cacheModule) return;
		const top = await run("git", ["rev-parse", "--show-toplevel"]);
		const common = await run("git", ["rev-parse", "--git-common-dir"]);
		const roots: string[] = [];
		if (top.code === 0) roots.push(top.stdout.trim());
		if (common.code === 0) {
			// Linked worktrees: toplevel is the worktree itself (whose .xtrm/
			// usually lacks hooks/) — fall back to the main checkout that owns
			// the common git dir. Plain repos resolve to the same root twice.
			const commonDir = resolve(cwd(), common.stdout.trim());
			if (commonDir.endsWith(`${sep}.git`)) roots.push(dirname(commonDir));
		}
		roots.push(cwd());
		for (const candidate of new Set(roots)) {
			const moduleUrl = pathToFileURL(join(candidate, CACHE_MODULE)).href;
			try {
				cacheModule = (await import(/* @vite-ignore */ moduleUrl)) as CacheModule;
				break;
			} catch {
				cacheModule = null;
			}
		}
		if (cacheModule) {
			mainRoot = cacheModule.resolveMainRoot(cwd());
			beadsCache = cacheModule.readCache(mainRoot);
		}
	};

	// Re-read the on-disk cache only — no subprocess refresh. Stale/unavailable is fine.
	const syncCache = (): void => {
		if (!cacheModule || !mainRoot) return;
		const next = cacheModule.readCache(mainRoot);
		if (next?.ts === beadsCache?.ts && next?.stale === beadsCache?.stale) return;
		beadsCache = next;
		requestRender?.();
	};

	const startCacheSync = (): void => {
		if (cacheSyncTimer) clearInterval(cacheSyncTimer);
		cacheSyncTimer = setInterval(syncCache, CACHE_TTL);
		cacheSyncTimer.unref?.();
	};

	const refreshRuntime = async (): Promise<void> => {
		if (refreshingRuntime || Date.now() - runtimeState.lastFetch < CACHE_TTL) return;
		refreshingRuntime = true;
		try {
			let branch: string | null = null;
			let gitStatus = "";
			const root = await run("git", ["rev-parse", "--show-toplevel"]);
			if (root.code === 0 && root.stdout.trim()) {
				const [branchResult, porcelainResult, abResult] = await Promise.all([
					run("git", ["branch", "--show-current"]),
					run("git", ["--no-optional-locks", "status", "--porcelain"]),
					run("git", ["--no-optional-locks", "rev-list", "--left-right", "--count", "@{upstream}...HEAD"]),
				]);
				branch = branchResult.code === 0 ? branchResult.stdout.trim() || null : null;
				gitStatus = porcelainResult.code === 0 ? parseGitFlags(porcelainResult.stdout) : "";
				if (abResult.code === 0) {
					const [behind, ahead] = abResult.stdout.trim().split(/\s+/).map(Number);
					gitStatus += ahead > 0 && behind > 0 ? "↕" : ahead > 0 ? "↑" : behind > 0 ? "↓" : "";
				}
			}
			runtimeState = { branch, gitStatus, lastFetch: Date.now() };
			requestRender?.();
		} finally {
			refreshingRuntime = false;
		}
	};

	const scheduleRuntimeRefresh = (delayMs = 0): void => {
		if (runtimeRefreshTimer) return;
		runtimeRefreshTimer = setTimeout(() => {
			runtimeRefreshTimer = null;
			void refreshRuntime();
		}, delayMs);
	};

	const applyFooter = (ctx: any): void => {
		capturedCtx = ctx;
		if (typeof ctx.ui?.setFooter !== "function") {
			footerDisabled = true;
			return;
		}
		ctx.ui.setFooter((tui: any, theme: any, footerData: any) => {
			const instanceRender = () => tui.requestRender();
			requestRender = instanceRender;
			branchChangeUnsub?.();
			const unsubscribe = footerData.onBranchChange(() => {
				runtimeState.lastFetch = 0;
				scheduleRuntimeRefresh();
			});
			branchChangeUnsub = unsubscribe;
			return {
				dispose() {
					unsubscribe?.();
					if (branchChangeUnsub === unsubscribe) branchChangeUnsub = null;
					if (requestRender === instanceRender) requestRender = null;
				},
				invalidate() {},
				render(width: number): string[] {
					let pwd = ctx.cwd || process.cwd();
					// Linked worktrees (.xtrm/worktrees/*): full paths are unreadably long —
					// collapse to <mainrepo>@<worktree-basename>.
					const wtRel = mainRoot ? relative(mainRoot, pwd) : "";
					if (wtRel && !wtRel.startsWith("..") && wtRel.includes(".xtrm/worktrees")) {
						pwd = `${basename(mainRoot)}@${basename(pwd)}`;
					} else {
						const home = process.env.HOME || process.env.USERPROFILE;
						if (home && pwd.startsWith(home)) pwd = `~${pwd.slice(home.length)}`;
					}
					const branch = runtimeState.branch || footerData.getGitBranch();
					if (branch) pwd += `(${branch}${runtimeState.gitStatus ? ` ${runtimeState.gitStatus}` : ""})`;

					const usage = ctx.getContextUsage();
					const model = ctx.model;
					const contextWindow = usage?.contextWindow ?? model?.contextWindow ?? 0;
					const percentValue = usage?.percent ?? 0;
					const contextDisplay = usage?.percent == null ? `?/${formatTokens(contextWindow)}` : `${percentValue.toFixed(1)}%/${formatTokens(contextWindow)}`;
					let modelDisplay = model?.id || "no-model";
					if (footerData.getAvailableProviderCount() > 1 && model) modelDisplay = `(${model.provider}) ${modelDisplay}`;
					// Neutral model: bold light-white, slightly dimmed. Only the effort
					// level below carries color. Raw SGR like XTRM_ACCENT — theme.fg()
					// only accepts named tokens.
					modelDisplay = `\x1b[1m\x1b[2m\x1b[97m${modelDisplay}\x1b[39m\x1b[22m`;
					// theme.bold is a no-op in pi TUI — use SGR bold directly for the thinking level.
					if (model?.reasoning) modelDisplay += ` ${XTRM_ACCENT}\x1b[1m${pi.getThinkingLevel() || "off"}\x1b[22m\x1b[39m`;

					const counts = beadsCache?.counts;
					let beadsDisplay = "";
					if (counts)	beadsDisplay = ` o:${counts.open} p:${counts.in_progress}${counts.blocked ? ` b:${counts.blocked}` : ""}`;

					const usageColor = percentValue > 90 ? "error" : percentValue > 70 ? "warning" : "dim";
					// Bold + default fg (not dim) so the path/branch reads first.
					const head = `\x1b[1m${pwd}\x1b[22m`;
					const line = `${head} ${theme.fg(usageColor, contextDisplay)} ${modelDisplay}${theme.fg("dim", beadsDisplay)}`;
					const lines = [truncateToWidth(line, width)];
					for (const renderBelow of footerSections.values()) {
						try {
							for (const sectionLine of renderBelow(width) ?? []) lines.push(truncateToWidth(sectionLine, width));
						} catch {
							// A faulty section must never break the statusline.
						}
					}
					return lines;
				},
			};
		});
	};

	const reapplyFooter = (ctx: any): void => {
		if (footerReapplyTimer) clearTimeout(footerReapplyTimer);
		footerReapplyTimer = setTimeout(() => {
			applyFooter(ctx);
			footerReapplyTimer = null;
		}, FOOTER_REAPPLY_DELAY_MS);
	};

	const reset = (): void => {
		runtimeState.lastFetch = 0;
		beadsCache = null;
		cacheModule = null;
		mainRoot = "";
	};

	pi.on("session_start", async (_event, ctx) => {
		capturedCtx = ctx;
		reset();
		await loadCacheModule();
		applyFooter(ctx);
		startCacheSync();
		reapplyFooter(ctx);
		scheduleRuntimeRefresh();
	});
	pi.on("session_switch", async (_event, ctx) => {
		capturedCtx = ctx;
		reset();
		await loadCacheModule();
		reapplyFooter(ctx);
		scheduleRuntimeRefresh();
	});
	pi.on("session_fork", async (_event, ctx) => {
		capturedCtx = ctx;
		reset();
		await loadCacheModule();
		reapplyFooter(ctx);
		scheduleRuntimeRefresh();
	});
	pi.on("model_select", async (_event, ctx) => reapplyFooter(ctx));
	pi.on("tool_result", async (event: any) => {
		const command = event?.input?.command;
		if (!command) return undefined;
		if (/\bbd\s+(close|update|create|claim|reopen)\b/.test(command)) {
			// Beads hooks regenerate the on-disk cache; just re-read it (no subprocess).
			syncCache();
		}
		if (/\bgit\s+/.test(command)) {
			runtimeState.lastFetch = 0;
			scheduleRuntimeRefresh(TOOL_RESULT_REFRESH_DELAY_MS);
		}
		return undefined;
	});
	pi.on("session_shutdown", async () => {
		clearFooterHook();
		for (const timer of [footerReapplyTimer, runtimeRefreshTimer]) if (timer) clearTimeout(timer);
		if (cacheSyncTimer) clearInterval(cacheSyncTimer);
		footerReapplyTimer = runtimeRefreshTimer = null;
		cacheSyncTimer = null;
		branchChangeUnsub?.();
		branchChangeUnsub = null;
		requestRender = null;
		footerDisabled = false;
	});
}
